/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef DEVICEERROR_H
#define DEVICEERROR_H

/* function declarations */
int send_deviceError_trap(void);

#endif /* DEVICEERROR_H */
