/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef IPADDRESSCONFLICT_H
#define IPADDRESSCONFLICT_H

/* function declarations */
int send_ipAddressConflict_trap(void);

#endif /* IPADDRESSCONFLICT_H */
