/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "deviceInfo/deviceSoftwareVersion.h"
#include "mibParameters.h"
#include "handler.h"

/**
 * \brief Initializes the deviceSoftwareVersion module
 */
void
init_deviceSoftwareVersion(void)
{
    const oid deviceSoftwareVersion_oid[] = { 1,3,6,1,4,1,35990,3,1,1,6 };

  g_debug("deviceSoftwareVersion initializing");

   netsnmp_register_read_only_instance(
        netsnmp_create_handler_registration("deviceSoftwareVersion", handle_deviceSoftwareVersion,
                               deviceSoftwareVersion_oid, OID_LENGTH(deviceSoftwareVersion_oid),
                               HANDLER_CAN_RONLY
        ));
}

/**
 * \brief calls appropriate handler for this parameter
 * \param handler the specific handler for this item
 * \param reqinfo the SNMP request
 * \param reuests the resuest information
 * \param mib_parameter the parameter of the MIB
 * \return SNMP_ERR_NOERROR or approriate code error
 */
int
handle_deviceSoftwareVersion(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    return handle_ROstring16(handler, reginfo, reqinfo, requests,  &deviceInfo.parameters[num_DeviceSWV]);
}
