/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "deviceInfo/deviceMode.h"
#include "mibParameters.h"
#include "handler.h"

/**
 * \brief Initializes the deviceMode module
 */
void init_deviceMode(void){
    const oid deviceMode_oid[] = { 1,3,6,1,4,1,35990,3,1,1,14 };

  g_debug("deviceMode initializing");

    netsnmp_register_instance(
        netsnmp_create_handler_registration("deviceMode", handle_deviceMode,
                               deviceMode_oid, OID_LENGTH(deviceMode_oid),
                               HANDLER_CAN_RWRITE
        ));
}

/**
 * \brief calls appropriate handler for this parameter
 * \param handler the specific handler for this item
 * \param reqinfo the SNMP request
 * \param reuests the resuest information
 * \param mib_parameter the parameter of the MIB
 * \return SNMP_ERR_NOERROR or approriate code error
 */
int handle_deviceMode( 	netsnmp_mib_handler *handler,
                        netsnmp_handler_registration *reginfo,
                        netsnmp_agent_request_info   *reqinfo,
                        netsnmp_request_info         *requests)
{

   /*checking type as it is done in MODE_SET_RESERVE1
    * is not enough, here we also want to check if
    * the integer is 1, 2 or 3. Otherwise, we return an error
    * indicating ot the user that the integer used is a bad value
    * for our deviceMode parameter.
    */
    if( (reqinfo->mode == MODE_SET_RESERVE2) &&( *(requests->requestvb->val.integer) <=0 || *(requests->requestvb->val.integer) >3)){
        netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_BADVALUE);
        return SNMP_ERR_BADVALUE;
    }else{
        return handle_RWinteger(handler, reginfo, reqinfo, requests, &(deviceInfo.parameters[num_DeviceMode]));
    }
}
