/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "../../include/deviceInfo/deviceFirmwareVersion.h"
#include "../../include/mibParameters.h"
#include "../../include/handler.h"

/* Initializes the deviceFirmwareVersion module */
void init_deviceFirmwareVersion(void){
 
    const oid deviceFirmwareVersion_oid[] = { 1,3,6,1,4,1,35990,3,1,1,7 };

    DEBUGMSGTL(("deviceFirmwareVersion", "Initializing\n"));

    netsnmp_register_read_only_instance(
        netsnmp_create_handler_registration("deviceFirmwareVersion", handle_deviceFirmwareVersion,
                               deviceFirmwareVersion_oid, OID_LENGTH(deviceFirmwareVersion_oid),
                               HANDLER_CAN_RONLY
        ));
}

int
handle_deviceFirmwareVersion(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
        return handle_ROstring16(handler, reginfo, reqinfo, requests, &deviceInfo.parameters[num_DeviceFV]);
}
