/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include <arpa/inet.h>
#include <sys/socket.h>
#include <ctype.h>
#include <glib-2.0/glib.h>
#include "../../include/mibParameters.h"
#include "../../include/deviceInfo/ethernetIfTable.h"


    /* Typical data structure for a row entry */
struct ethernetIfTableEntry {
    /* Index values */
    long ethernetIfIndex;

    /* Column values */
    long ethernetIfSpeed;
    char ethernetIfMacAddress[6];
    size_t ethernetIfMacAddress_len;
    in_addr_t ethernetIfIpAddress;
    in_addr_t old_ethernetIfIpAddress;
    in_addr_t ethernetIfSubnetMask;
    in_addr_t old_ethernetIfSubnetMask;
    in_addr_t ethernetIfIpAddressConflict;
    in_addr_t old_ethernetIfIpAddressConflict;

    /* Illustrate using a simple linked list */
    int   valid;
    struct ethernetIfTableEntry *next;
};

struct ethernetIfTableEntry  *ethernetIfTable_head;

/* create a new row in the (unsorted) table */
struct ethernetIfTableEntry * ethernetIfTableEntry_create(  long  ethernetIfIndex,
                                                            long ethernetIfSpeed,
                                                            u_char ethernetIfMacAddress[6],
                                                            size_t ethernetIfMacAddress_len,
                                                            in_addr_t ethernetIfIpAddress,
                                                            in_addr_t ethernetIfSubnetMask,
                                                            in_addr_t ethernetIfIpAddressConflict)
{
    struct ethernetIfTableEntry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct ethernetIfTableEntry);
    if (!entry)
        return NULL;

    entry->ethernetIfIndex = ethernetIfIndex;
    entry->next = ethernetIfTable_head;
    entry->ethernetIfSpeed = ethernetIfSpeed;

    memcpy(entry->ethernetIfMacAddress, ethernetIfMacAddress,ethernetIfMacAddress_len );
    entry->ethernetIfMacAddress_len = ethernetIfMacAddress_len;

    entry->ethernetIfIpAddress = ethernetIfIpAddress;

    entry->ethernetIfSubnetMask = ethernetIfSubnetMask;

    entry->ethernetIfIpAddressConflict = ethernetIfIpAddressConflict;

    entry->valid = 1;

    ethernetIfTable_head = entry;

    return entry;
}

/* This function converts a char* representing a MacAddress to an array of bytes.
 * As the char* represent a MAC address it should have a pattern as:
 * 'XX:XX:XX:XX:XX:XX\0'
 * It will be used to convert the ethernetIfMacAddress
 * from the initial char* value to an array of 6 bytes
 * using the character to creates the right bytes
 */
void MAC_to_byte_array(u_char dest[6], u_char* source){
    /*we declare a byte that will be used to fill our destination array*/
   u_char result;
    int i=0;
    int j = 0;
    /* The format of a Mac address is XX:XX:XX:XX:XX:XX, so we access
     * character number 0, then 3, then 6, then 9, then 11 and finally 15
     */
    for(i=0; i<strlen((char*) source); i=i+3){
        result = toupper(source[i]);
        if ( (result >= 'A') && (result<= 'F')){
            result = result - 55 ; //get the corresponding hexadecimal value of the character
        }
        else{ /*if result is not a letter, it a number*/
            result = result - 48;
        }
        result = (result<<4);
        if (toupper(source[i+1]) <= 'F' && toupper(source[i+1]) >= 'A'){
            result += (toupper(source[i+1]) -55);
        }else{
            result += source[i+1] - 48;
        }
        dest[j] = result;
        j++;
    }
}

/* This function initialize the content of the Entry of he ethernetIfTable
 * with the content of the array defined in mib_parameter.h, and initialize
 * with the configuration file
 */
void ethernetIfTable_fill(int entryCount){
    int i=0; /*loop variable*/
    u_char Mac[6];
    for(i=0; i < entryCount; i++){
        MAC_to_byte_array( Mac,(u_char*) deviceInfo.parameters[num_ethernetIfMacAddress]._value.array_string_val[i]);
        struct ethernetIfTableEntry* entry = ethernetIfTableEntry_create(i+1, deviceInfo.parameters[num_ethernetIfSpeed]._value.array_int_val[i],
                                                                         Mac, 6,
                                                                         inet_addr(deviceInfo.parameters[num_ethernetIfIpAddress]._value.array_string_val[i]),
                                                                         inet_addr(deviceInfo.parameters[num_ethernetIfSubnetMask]._value.array_string_val[i]),
                                                                         inet_addr(deviceInfo.parameters[num_ethernetIfIpAddressConflict]._value.array_string_val[i]));
        entry->valid = 1;
    }
}
/** Initialize the ethernetIfTable table by defining its contents and how it's structured */
static void initialize_table_ethernetIfTable(void)
{
    const oid ethernetIfTable_oid[] = {1,3,6,1,4,1,35990,3,1,1,12};
    const size_t ethernetIfTable_oid_len   = OID_LENGTH(ethernetIfTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("ethernetIfTable:init", "initializing table ethernetIfTable\n"));

    reg = netsnmp_create_handler_registration(
              "ethernetIfTable",     ethernetIfTable_handler,
              ethernetIfTable_oid, ethernetIfTable_oid_len,
              HANDLER_CAN_RWRITE
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: ethernetIfIndex */
                           0);
    table_info->min_column = COLUMN_ETHERNETIFSPEED;
    table_info->max_column = COLUMN_ETHERNETIFIPADDRESSCONFLICT;

    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = ethernetIfTable_get_first_data_point;
    iinfo->get_next_data_point  = ethernetIfTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;

    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
    ethernetIfTable_fill(deviceInfo.parameters[num_ethernetIFnumber]._value.int_val);

}

/** Initializes the ethernetIfTable module */
void
init_ethernetIfTable(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_ethernetIfTable();
}

/* Remove a row from the table
 * I leave the code here, however for our application, there is not possibility
 * to remove a row from the table.
 * the functionnality exits, but should not be implemented for now
 */
#define ALLOW_REMOVING_ROW 0
#if ALLOW_REMOVING_ROW
void ethernetIfTable_removeEntry( struct ethernetIfTableEntry *entry ) {
    struct ethernetIfTableEntry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = ethernetIfTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        ethernetIfTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}
#endif // ALLOW_REMOVING_ROW

netsnmp_variable_list *
ethernetIfTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct ethernetIfTableEntry *entry = (struct ethernetIfTableEntry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->ethernetIfIndex );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}

/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
ethernetIfTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = ethernetIfTable_head;
    return ethernetIfTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}




/** handles requests for the ethernetIfTable table */
int
ethernetIfTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct ethernetIfTableEntry          *table_entry;
    int ret;
    DEBUGMSGTL(("ethernetIfTable:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct ethernetIfTableEntry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
            switch (table_info->colnum) {
            case COLUMN_ETHERNETIFSPEED:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->ethernetIfSpeed);

            break;
            case COLUMN_ETHERNETIFMACADDRESS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->ethernetIfMacAddress,
                                          table_entry->ethernetIfMacAddress_len);
                break;
            case COLUMN_ETHERNETIFIPADDRESS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_IPADDRESS,
                                         (u_char*) &table_entry->ethernetIfIpAddress, 4 );
                break;
            case COLUMN_ETHERNETIFSUBNETMASK:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_IPADDRESS,
                                         (u_char*) &table_entry->ethernetIfSubnetMask, 4 );
                break;
            case COLUMN_ETHERNETIFIPADDRESSCONFLICT:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_IPADDRESS,
                                         (u_char*) &table_entry->ethernetIfIpAddressConflict, 4 );
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;
        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        for (request=requests; request; request=request->next) {
            table_entry = (struct ethernetIfTableEntry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
            switch (table_info->colnum) {
            case COLUMN_ETHERNETIFIPADDRESS:
                ret = netsnmp_check_vb_type( request->requestvb, ASN_IPADDRESS );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_ETHERNETIFSUBNETMASK:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_type( request->requestvb, ASN_IPADDRESS );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_ETHERNETIFIPADDRESSCONFLICT:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_type( request->requestvb, ASN_IPADDRESS );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            default:
                netsnmp_set_request_error( reqinfo, request,
                                           SNMP_ERR_NOTWRITABLE );
                return SNMP_ERR_NOERROR;
            }
        }
        break;

    case MODE_SET_RESERVE2:
        break;

    case MODE_SET_FREE:
        break;

    case MODE_SET_ACTION:
        /* On i386 the host Byte order is Least significant Byte first (Litlle Endian), whereas the
        * network byte order, as used on the Internet is Most Significant byte first (Big Endian)
        * to check the integer type of the value send to the subAgent, we must first convert
        * the integer received from Little Endian to Big Endian
        */
        for (request=requests; request; request=request->next) {
            table_entry = (struct ethernetIfTableEntry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
            switch (table_info->colnum) {
            case COLUMN_ETHERNETIFIPADDRESS:
                table_entry->old_ethernetIfIpAddress 			= table_entry->ethernetIfIpAddress;
                table_entry->ethernetIfIpAddress     			= *request->requestvb->val.integer;
                break;
            case COLUMN_ETHERNETIFSUBNETMASK:
                table_entry->old_ethernetIfSubnetMask 			= table_entry->ethernetIfSubnetMask;
                table_entry->ethernetIfSubnetMask     			= *request->requestvb->val.integer;
                break;
            case COLUMN_ETHERNETIFIPADDRESSCONFLICT:
                table_entry->old_ethernetIfIpAddressConflict 	= table_entry->ethernetIfIpAddressConflict;
                table_entry->ethernetIfIpAddressConflict     	= *request->requestvb->val.integer;
                break;
            }
        }
        break;

    case MODE_SET_UNDO:
        for (request=requests; request; request=request->next) {
            table_entry = (struct ethernetIfTableEntry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);

            switch (table_info->colnum) {
            case COLUMN_ETHERNETIFIPADDRESS:
                table_entry->ethernetIfIpAddress     			= table_entry->old_ethernetIfIpAddress;
                table_entry->old_ethernetIfIpAddress 			= 0;
                break;
            case COLUMN_ETHERNETIFSUBNETMASK:
                table_entry->ethernetIfSubnetMask     			= table_entry->old_ethernetIfSubnetMask;
                table_entry->old_ethernetIfSubnetMask 			= 0;
                break;
            case COLUMN_ETHERNETIFIPADDRESSCONFLICT:
                table_entry->ethernetIfIpAddressConflict     	= table_entry->old_ethernetIfIpAddressConflict;
                table_entry->old_ethernetIfIpAddressConflict 	= 0;
                break;
            }
        }
        break;

    case MODE_SET_COMMIT:
        break;
    }
    return SNMP_ERR_NOERROR;
}
