/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef DEVICEMODE_H
#define DEVICEMODE_H

/* function declarations */
void init_deviceMode(void);
Netsnmp_Node_Handler handle_deviceMode;

#endif /* DEVICEMODE_H */
