/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef ETHERNETIFTABLE_H
#define ETHERNETIFTABLE_H

/* function declarations */
void init_ethernetIfTable(void);
gboolean init_ethernet(const char* iface);
void MAC_to_byte_array(u_char dest[6], u_char* source);
void init_ethernetIfTable_content(int entryNumber);
void initialize_table_ethernetIfTable(void);
void initialize_ethernetIfTableEntry();
Netsnmp_Node_Handler 		ethernetIfTable_handler;
Netsnmp_First_Data_Point 	ethernetIfTable_get_first_data_point;
Netsnmp_Next_Data_Point 	ethernetIfTable_get_next_data_point;


/* column number definitions for table ethernetIfTable */
       #define COLUMN_ETHERNETIFINDEX                   1
       #define COLUMN_ETHERNETIFSPEED		            2
       #define COLUMN_ETHERNETIFMACADDRESS	        	3
       #define COLUMN_ETHERNETIFIPADDRESS	           	4
       #define COLUMN_ETHERNETIFSUBNETMASK	        	5
       #define COLUMN_ETHERNETIFIPADDRESSCONFLICT		6
#endif /* ETHERNETIFTABLE_H */
