/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef CHANNELRESET_H
#define CHANNELRESET_H

/* function declarations */
void init_channelReset(void);
Netsnmp_Node_Handler handle_channelReset;

#endif /* CHANNELRESET_H */
