/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef CHANNELTABLE_H
#define CHANNELTABLE_H

/* function declarations */
void init_channelTable(void);
void initialize_table_channelTable(void);
Netsnmp_Node_Handler channelTable_handler;
Netsnmp_First_Data_Point  channelTable_get_first_data_point;
Netsnmp_Next_Data_Point   channelTable_get_next_data_point;
NetsnmpCacheLoad channelTable_load;
NetsnmpCacheFree channelTable_free;
#define CHANNELTABLE_TIMEOUT  60

/* column number definitions for table channelTable */
       #define COLUMN_CHANNELINDEX							1
       #define COLUMN_CHANNELTYPE							2
       #define COLUMN_CHANNELUSERDESC						3
       #define COLUMN_CHANNELSTATUS							4
       #define COLUMN_CHANNELVIDEOFORMATINDEX				5
       #define COLUMN_CHANNELVIDEOFORMAT					6
       #define COLUMN_CHANNELVIDEOSAMPLING					7
       #define COLUMN_CHANNELVIDEOBITDEPTH					8
       #define COLUMN_CHANNELFPS							9
       #define COLUMN_CHANNELCOLORIMETRY					10
       #define COLUMN_CHANNELINTERLACED						11
       #define COLUMN_CHANNELCOMPRESSIONFACTOR				12
       #define COLUMN_CHANNELCOMPRESSIONRATE				13
       #define COLUMN_CHANNELHORZRES						14
       #define COLUMN_CHANNELVERTRES						15
       #define COLUMN_CHANNELROIORIGINTOP					16
       #define COLUMN_CHANNELROIORIGINLEFT					17
       #define COLUMN_CHANNELROIEXTENTBOTTOM				18
       #define COLUMN_CHANNELROIEXTENTRIGHT					19
       #define COLUMN_CHANNELRTPPT							20
       #define COLUMN_CHANNELRECEIVEIPADDRESS				21
       #define COLUMN_CHANNELINTERPACKETDELAY				22
       #define COLUMN_CHANNELSAPMESSAGEINTERVAL				23
       #define COLUMN_CHANNELDEFAULTVIDEOFORMATINDEX		24
       #define COLUMN_CHANNELDEFAULTRECEIVEIPADDRESS		25
#endif /* CHANNELTABLE_H */
