/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef CHANNELNUMBER_H
#define CHANNELNUMBER_H

/* function declarations */
void init_channelNumber(void);
Netsnmp_Node_Handler handle_channelNumber;

#endif /* CHANNELNUMBER_H */
