/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef VIDEOFORMATNUMBER_H
#define VIDEOFORMATNUMBER_H

/* function declarations */
void init_videoFormatNumber(void);
Netsnmp_Node_Handler handle_videoFormatNumber;

#endif /* VIDEOFORMATNUMBER_H */
