/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef VIDEOFORMATTABLE_H
#define VIDEOFORMATTABLE_H

/* function declarations */

void init_videoFormatTable(void);
void initialize_table_videoFormatTable(void);
Netsnmp_Node_Handler videoFormatTable_handler;
Netsnmp_First_Data_Point  videoFormatTable_get_first_data_point;
Netsnmp_Next_Data_Point   videoFormatTable_get_next_data_point;
NetsnmpCacheLoad videoFormatTable_load;
NetsnmpCacheFree videoFormatTable_free;

#define VIDEOFORMATTABLE_TIMEOUT  60

/* column number definitions for table videoFormatTable */
       #define COLUMN_VIDEOFORMATINDEX					1
       #define COLUMN_VIDEOFORMATTYPE					2
       #define COLUMN_VIDEOFORMATSTATUS					3
       #define COLUMN_VIDEOFORMATBASE					4
       #define COLUMN_VIDEOFORMATSAMPLING				5
       #define COLUMN_VIDEOFORMATBITDEPTH				6
       #define COLUMN_VIDEOFORMATFPS					7
       #define COLUMN_VIDEOFORMATCOLORIMETRY			8
       #define COLUMN_VIDEOFORMATINTERLACED				9
       #define COLUMN_VIDEOFORMATCOMPRESSIONFACTOR		10
       #define COLUMN_VIDEOFORMATCOMPRESSIONRATE		11
       #define COLUMN_VIDEOFORMATMAXHORZRES				12
       #define COLUMN_VIDEOFORMATMAXVERTRES				13
       #define COLUMN_VIDEOFORMATROIHORZRES				14
       #define COLUMN_VIDEOFORMATROIVERTRES				15
       #define COLUMN_VIDEOFORMATROIORIGINTOP			16
       #define COLUMN_VIDEOFORMATROIORIGINLEFT			17
       #define COLUMN_VIDEOFORMATROIEXTENTBOTTOM		18
       #define COLUMN_VIDEOFORMATROIEXTENTRIGHT			19
       #define COLUMN_VIDEOFORMATRTPPT					20

/* Typical data structure for a row entry */
struct videoFormatTable_entry {
	/* Index values */
	long videoFormatIndex;

	/* Column values */
	long videoFormatType;
	long videoFormatStatus;
	char* videoFormatBase; /* Should be a 16 bytes string */
	size_t videoFormatBase_len;
	char* videoFormatSampling; /* Should be a 16 bytes string */
	size_t videoFormatSampling_len;
	long videoFormatBitDepth;
	long videoFormatFps;
	char* videoFormatColorimetry; /* Should be a 16 bytes string */
	size_t videoFormatColorimetry_len;
	long videoFormatInterlaced;
	long videoFormatCompressionFactor;
	long old_videoFormatCompressionFactor;
	long videoFormatCompressionRate;
	long old_videoFormatCompressionRate;
	long videoFormatMaxHorzRes;
	long videoFormatMaxVertRes;
	long videoFormatRoiHorzRes;
	long old_videoFormatRoiHorzRes;
	long videoFormatRoiVertRes;
	long old_videoFormatRoiVertRes;
	long videoFormatRoiOriginTop;
	long old_videoFormatRoiOriginTop;
	long videoFormatRoiOriginLeft;
	long old_videoFormatRoiOriginLeft;
	long videoFormatRoiExtentBottom;
	long old_videoFormatRoiExtentBottom;
	long videoFormatRoiExtentRight;
	long old_videoFormatRoiExtentRight;
	long videoFormatRtpPt;
	long old_videoFormatRtpPt;
	
	/* a stream assoicated to the channel */
	gpointer stream_datas;
	/* Illustrate using a simple linked list */
	int   valid;
	struct videoFormatTable_entry *next;
};

struct videoFormatTable_entry  *videoFormatTable_head;

struct videoFormatTable_entry * videoFormatTable_createEntry( 	long  videoFormatIndex, 			long videoFormatType,
																long videoFormatStatus,				char* videoFormatBase,
																char* videoFormatSampling,			long videoFormatBitDepth,
																long videoFormatFps,				char* videoFormatColorimetry,
																long videoFormatInterlaced,	 		long videoFormatCompressionFactor,
																long videoFormatCompressionRate, 	long videoFormatMaxHorzRes,
																long videoFormatMaxVertRes,			long videoFormatRoiHorzRes,
																long videoFormatRoiVertRes, 		long videoFormatRoiOriginTop,
																long videoFormatRoiOriginLeft,		long videoFormatRoiExtentBottom,
																long videoFormatRoiExtentRight, 	long videoFormatRtpPt, 
																gpointer stream_datas);

struct videoFormatTable_entry * videoFormatTable_getEntry(int index);

#endif /* VIDEOFORMATTABLE_H */
