/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "../include/ethernetIfEntry.h"
#include "../include/ethernetIfIndex.h"
#include "../include/ethernetIfNumber.h"


#include "../include/ethernetIfSpeed.h"
#include "../include/ethernetIfMacAddress.h"
#include "../include/ethernetIfIpAddress.h"
#include "../include/ethernetIfSubnetMask.h"
#include "../include/ethernetIfIpAddressConflict.h"



/** Initializes the ethernetIfEntry module */
void
init_ethernetIfEntry(void)
{
    const oid ethernetIfIndex_oid[] = { 1,3,6,1,4,1,35990,3,1,1,12,1,1 };
    const oid ethernetIfSpeed_oid[] = { 1,3,6,1,4,1,35990,3,1,1,12,1,2 };
    const oid ethernetIfMacAddress_oid[] = { 1,3,6,1,4,1,35990,3,1,1,12,1,3 };
    const oid ethernetIfIpAddress_oid[] = { 1,3,6,1,4,1,35990,3,1,1,12,1,4 };
    const oid ethernetIfSubnetMask_oid[] = { 1,3,6,1,4,1,35990,3,1,1,12,1,5 };
    const oid ethernetIfIpAddressConflict_oid[] = { 1,3,6,1,4,1,35990,3,1,1,12,1,6 };

  DEBUGMSGTL(("ethernetIfEntry", "Initializing\n"));

    /*netsnmp_register_read_only_instance(
        netsnmp_create_handler_registration("ethernetIfIndex", handle_ethernetIfIndex,
                               ethernetIfIndex_oid, OID_LENGTH(ethernetIfIndex_oid),
                               HANDLER_CAN_RONLY ));*/

    netsnmp_register_read_only_instance(
        netsnmp_create_handler_registration("ethernetIfSpeed", handle_ethernetIfSpeed,
                               ethernetIfSpeed_oid, OID_LENGTH(ethernetIfSpeed_oid),
                               HANDLER_CAN_RONLY ));

    netsnmp_register_read_only_instance(
        netsnmp_create_handler_registration("ethernetIfMacAddress", handle_ethernetIfMacAddress,
                               ethernetIfMacAddress_oid, OID_LENGTH(ethernetIfMacAddress_oid),
                               HANDLER_CAN_RONLY ));

    netsnmp_register_instance(
        netsnmp_create_handler_registration("ethernetIfIpAddress", handle_ethernetIfIpAddress,
                               ethernetIfIpAddress_oid, OID_LENGTH(ethernetIfIpAddress_oid),
                               HANDLER_CAN_RWRITE ));

    netsnmp_register_instance(
        netsnmp_create_handler_registration("ethernetIfSubnetMask", handle_ethernetIfSubnetMask,
                               ethernetIfSubnetMask_oid, OID_LENGTH(ethernetIfSubnetMask_oid),
                               HANDLER_CAN_RWRITE ));

    netsnmp_register_instance(
        netsnmp_create_handler_registration("ethernetIfIpAddressConflict", handle_ethernetIfIpAddressConflict,
                               ethernetIfIpAddressConflict_oid, OID_LENGTH(ethernetIfIpAddressConflict_oid),
                               HANDLER_CAN_RWRITE ));

}
