/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef ETHERNETIFSUBNETMASK_H
#define ETHERNETIFSUBNETMASK_H

/* function declarations */
void init_ethernetIfSubnetMask(void);
Netsnmp_Node_Handler handle_ethernetIfSubnetMask;

#endif /* ETHERNETIFSUBNETMASK_H */
