/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef ETHERNETIFMACADDRESS_H
#define ETHERNETIFMACADDRESS_H

/* function declarations */
void init_ethernetIfMacAddress(void);
Netsnmp_Node_Handler handle_ethernetIfMacAddress;

#endif /* ETHERNETIFMACADDRESS_H */
