/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef ETHERNETIFENTRY_H
#define ETHERNETIFENTRY_H

/* function declarations */
void init_ethernetIfEntry(void);
Netsnmp_Node_Handler handle_ethernetIfIndex;
Netsnmp_Node_Handler handle_ethernetIfSpeed;
Netsnmp_Node_Handler handle_ethernetIfMacAddress;
Netsnmp_Node_Handler handle_ethernetIfIpAddress;
Netsnmp_Node_Handler handle_ethernetIfSubnetMask;
Netsnmp_Node_Handler handle_ethernetIfIpAddressConflict;

#endif /* ETHERNETIFENTRY_H */
