/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef ETHERNETIFSPEED_H
#define ETHERNETIFSPEED_H

/* function declarations */
void init_ethernetIfSpeed(void);
Netsnmp_Node_Handler handle_ethernetIfSpeed;

#endif /* ETHERNETIFSPEED_H */
