/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef ETHERNETIFIPADDRESS_H
#define ETHERNETIFIPADDRESS_H

/* function declarations */
void init_ethernetIfIpAddress(void);
Netsnmp_Node_Handler handle_ethernetIfIpAddress;

#endif /* ETHERNETIFIPADDRESS_H */
