/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "../include/ethernetIfIndex.h"
#include <errno.h>

/*value of deviceType*/
/* It should be an integer
 * serviceProvider(1),
 * serviceUser(2),
 * both(3)
 */
 /*by default it is set to normal serviceProvider*/

void init_ethernetIfIndex(void){
    ethernetIfIndex = malloc(sizeof(int)* 255);
    if(ethernetIfIndex == NULL){
        strerror(ENOMEM); /*we should not get to that point, otherwise there is a problem with the memory handling*/
        exit(ENOMEM); /*if there is no place left for memory allocation, there is no point keep on running the subAgent*/
    }
}
