/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef ETHERNETIFIPADDRESSCONFLICT_H
#define ETHERNETIFIPADDRESSCONFLICT_H

/* function declarations */
void init_ethernetIfIpAddressConflict(void);
Netsnmp_Node_Handler handle_ethernetIfIpAddressConflict;

#endif /* ETHERNETIFIPADDRESSCONFLICT_H */
