/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "../../include/videoFormatInfo/videoFormatNumber.h"
#include "../../include/mibParameters.h"
#include "../../include/handler.h"

/** Initializes the videoFormatNumber module */
void
init_videoFormatNumber(void)
{
    const oid videoFormatNumber_oid[] = { 1,3,6,1,4,1,35990,3,1,2,1 };

  DEBUGMSGTL(("videoFormatNumber", "Initializing\n"));

   	 netsnmp_register_read_only_instance(
        netsnmp_create_handler_registration("videoFormatNumber", handle_videoFormatNumber,
                               videoFormatNumber_oid, OID_LENGTH(videoFormatNumber_oid),
                               HANDLER_CAN_RONLY
        						));
}

int
handle_videoFormatNumber(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    return handle_ROinteger(handler, reginfo, reqinfo, requests, &videoFormatNumber);
}


