/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef DEVICESOFTWAREVERSION_H
#define DEVICESOFTWAREVERSION_H

/* function declarations */
void init_deviceSoftwareVersion(void);
Netsnmp_Node_Handler handle_deviceSoftwareVersion;

#endif /* DEVICESOFTWAREVERSION_H */
