/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef DEVICEFIRMWAREVERSION_H
#define DEVICEFIRMWAREVERSION_H

/* function declarations */
void init_deviceFirmwareVersion(void);
Netsnmp_Node_Handler handle_deviceFirmwareVersion;

#endif /* DEVICEFIRMWAREVERSION_H */
