/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef ETHERNETIFNUMBER_H
#define ETHERNETIFNUMBER_H

/* function declarations */

void init_ethernetIfNumber(void);
Netsnmp_Node_Handler handle_ethernetIfNumber;

#endif /* ETHERNETIFNUMBER_H */
