/*
 * Licence: GPL
 * Created: Thu, 14 Jan 2016 12:05:31 +0100
 * Main authors:
 *     - hoel <hvasseur@openwide.fr>
 */

/*
 * Note: this file originally auto-generated by mib2c using
 *
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "../include/deviceType.h"
#include "../include/mibParameters.h"


/*value of deviceType*/
/* It should be an integer
 * serviceProvider(1),
 * serviceUser(2),
 * both(3)
 */
 /*by default it is set to normal serviceProvider*/
//static int deviceType = 1;

void init_deviceType(void)
{
    static oid      deviceType_oid[] = { 1,3,6,1,4,1,35990,3,1,1,9 };

    /*
     * a debugging statement.  Run the agent with -DdeviceType to see
     * the output of this debugging statement.
     */
    DEBUGMSGTL(("deviceType",
                "Initializing the deviceType module\n"));

    /*
     * the line below registers our variables defined above as
     * accessible and makes it writable.  A read only version of any
     * of these registration would merely call
     * register_read_only_long_instance() instead.  The functions
     * called below should be consistent with your MIB, however.
     *
     * If we wanted a callback when the value was retrieved or set
     * (even though the details of doing this are handled for you),
     * you could change the NULL pointer below to a valid handler
     * function.
     */
    DEBUGMSGTL(("deviceType",
                "Initalizing deviceType scalar integer.  Default value = %d\n",
                deviceType));

    netsnmp_register_read_only_int_instance("deviceType",
                                            deviceType_oid,
                                            OID_LENGTH(deviceType_oid),
                                            NULL, handle_deviceType);

    DEBUGMSGTL(("deviceType",
                "Done initalizing deviceType module\n"));
}


int
handle_deviceType(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER, &deviceType, 2);
            break;
        /*there are no other case to code as this is a Read-only parameter*/

        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_deviceType\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

