/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "../include/deviceMibVersion.h"
#include "../include/handler.h"
#include "../include/mibParameters.h"


/** Initializes the deviceMibVersion module */
void
init_deviceMibVersion(void)
{
    const oid deviceMibVersion_oid[] = { 1,3,6,1,4,1,35990,3,1,1,8 };

  DEBUGMSGTL(("deviceMibVersion", "Initializing\n"));

    netsnmp_register_read_only_instance(
        netsnmp_create_handler_registration("deviceMibVersion", handle_deviceMibVersion,
                               deviceMibVersion_oid, OID_LENGTH(deviceMibVersion_oid),
                               HANDLER_CAN_RONLY
        ));
}

int
handle_deviceMibVersion(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    return handle_ROstring16(handler, reginfo, reqinfo, requests, "deviceMibVersion" , deviceInfo.parameters[num_DeviceMibV]._value.string_val);

}
