/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "../include/deviceManufacturer.h"
#include "../include/handler.h"
#include "../include/mibParameters.h"


/** Initializes the deviceManufacturer module */
void
init_deviceManufacturer(void)
{
    const oid deviceManufacturer_oid[] = { 1,3,6,1,4,1,35990,3,1,1,2 };

  DEBUGMSGTL(("deviceManufacturer", "Initializing\n"));

    netsnmp_register_read_only_instance(
        netsnmp_create_handler_registration("deviceManufacturer", handle_deviceManufacturer,
                               deviceManufacturer_oid, OID_LENGTH(deviceManufacturer_oid),
                               HANDLER_CAN_RONLY ));
}

int
handle_deviceManufacturer(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    return handle_ROstring64(handler, reginfo, reqinfo, requests, "deviceManufacturer" , deviceInfo.parameters[num_DeviceManu]._value.string_val);
}
