/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "../include/deviceHardwareVersion.h"
#include "../include/handler.h"
#include "../include/mibParameters.h"



/** Initializes the deviceHardwareVersion module */
void
init_deviceHardwareVersion(void)
{
    const oid deviceHardwareVersion_oid[] = { 1,3,6,1,4,1,35990,3,1,1,5 };

  DEBUGMSGTL(("deviceHardwareVersion", "Initializing\n"));

   netsnmp_register_read_only_instance(
        netsnmp_create_handler_registration("deviceHardwareVersion", handle_deviceHardwareVersion,
                               deviceHardwareVersion_oid, OID_LENGTH(deviceHardwareVersion_oid),
                               HANDLER_CAN_RONLY
        ));
}

int
handle_deviceHardwareVersion(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    return handle_ROstring16(handler, reginfo, reqinfo, requests, "deviceHardwareVersion" , deviceInfo.deviceHardwareVersion);
}
