/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "../include/devicePartNumber.h"
#include "../include/handler.h"
#include "../include/mibParameters.h"



/** Initializes the devicePartNumber module */
void
init_devicePartNumber(void)
{
    const oid devicePartNumber_oid[] = { 1,3,6,1,4,1,35990,3,1,1,3 };

  DEBUGMSGTL(("devicePartNumber", "Initializing\n"));

    netsnmp_register_read_only_instance(
        netsnmp_create_handler_registration("devicePartNumber", handle_devicePartNumber,
                               devicePartNumber_oid, OID_LENGTH(devicePartNumber_oid),
                               HANDLER_CAN_RONLY
        ));
}

int
handle_devicePartNumber(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    return handle_ROstring32(handler, reginfo, reqinfo, requests, "devicePartNumber" , deviceInfo.parameters[num_DevicePartNum]._value.string_val);
}
