/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "../include/ethernetIfSubnetMask.h"

/*value of ethernetIfSubnetMask*/
/* It should be a string of exactly 4 bytes*/
u_char ethernetIfSubnetMask[4] = {00, 00, 00, 00};

/** Initializes the ethernetIfSubnetMask module */
void init_ethernetIfSubnetMask(void)
{
    const oid ethernetIfSubnetMask_oid[] = { 1,3,6,1,4,1,35990,3,1,1,12,1,5 };

  DEBUGMSGTL(("ethernetIfSubnetMask", "Initializing\n"));

    netsnmp_register_instance(
        netsnmp_create_handler_registration("ethernetIfSubnetMask", handle_ethernetIfSubnetMask,
                               ethernetIfSubnetMask_oid, OID_LENGTH(ethernetIfSubnetMask_oid),
                               HANDLER_CAN_RWRITE
        ));
}

int handle_ethernetIfSubnetMask(netsnmp_mib_handler *handler,
                                netsnmp_handler_registration *reginfo,
                                netsnmp_agent_request_info   *reqinfo,
                                netsnmp_request_info         *requests)
{
    u_char * old_ethernetIfSubnetMask = NULL; /* this will be used to perform UNDO*/
    int i=0; /*this is needed as a loop variable to fill our array ethernetIfSubnetMask with the value the user send through snmp set*/
    int ret;
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_IPADDRESS,
                                     ethernetIfSubnetMask, 4);
            break;

        /*
         * SET REQUEST
         *
         * multiple states in the transaction.  See:
         * http://www.net-snmp.org/tutorial-5/toolkit/mib_module/set-actions.jpg
         */
        case MODE_SET_RESERVE1:
            /* or you could use netsnmp_check_vb_type_and_size instead */
            ret = netsnmp_check_vb_type(requests->requestvb, ASN_IPADDRESS);
            if ( ret != SNMP_ERR_NOERROR ) {
                netsnmp_set_request_error(reqinfo, requests, ret);
            }
            break;

        case MODE_SET_RESERVE2:
            /* XXX malloc "undo" storage buffer */
            old_ethernetIfSubnetMask =  (u_char*) netsnmp_memdup((u_char *) & ethernetIfSubnetMask,  sizeof(ethernetIfSubnetMask));
            if (old_ethernetIfSubnetMask == NULL) {
                netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_RESOURCEUNAVAILABLE);
            }else{
                old_ethernetIfSubnetMask = ethernetIfSubnetMask;
            }
            break;



        case MODE_SET_FREE:
            /* XXX: free resources allocated in RESERVE1 and/or
               RESERVE2.  Something failed somewhere, and the states
               below won't be called. */
            free(old_ethernetIfSubnetMask); /*free resources allocated in RESERVE2*/
            break;

        case MODE_SET_ACTION:
            /* XXX: perform the value change here */
            for(i=0; i<sizeof(ethernetIfSubnetMask)/sizeof(u_char); i++){
                ethernetIfSubnetMask[i] = requests->requestvb->val.string[i];
            }
            /*Send a message during debug to inform the update had been performed*/
            DEBUGMSGTL(("ethernetIfSubnetMask", "updated delay_time -> %s\n", ethernetIfSubnetMask));
            /*get possible errors*/
            ret = netsnmp_check_requests_error(requests);
            if (ret != SNMP_ERR_NOERROR) {
                netsnmp_set_request_error(reqinfo, requests, ret);
            }
            break;

        case MODE_SET_COMMIT:
            /* XXX: delete temporary storage
            if ( XXX: error? ) {
                 try _really_really_ hard to never get to this point
                netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_COMMITFAILED);
            }*/
            break;

        case MODE_SET_UNDO:
            /* XXX: UNDO and return to previous value for the object */
            memcpy(ethernetIfSubnetMask, old_ethernetIfSubnetMask, 4);
             ret = netsnmp_check_requests_error(requests);
            if (ret != SNMP_ERR_NOERROR) {
                /* try _really_really_ hard to never get to this point */
                netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_UNDOFAILED);
            }
            break;

        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_ethernetIfSubnetMask\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }
    return SNMP_ERR_NOERROR;
}
