/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "../include/ethernetIfTable.h"
#include <arpa/inet.h>

/* This is the initialization of the default values content
 * of the ethernetIfTable. This is only temporary. In a further
 * implementation, those values will be set from the .conf file
 * associated to the subagent
 */

    long ethernetIfIndex =                      1; /*default index*/
    long ethernetIfSpeed =                      1000; /*default speed value, set here as an example*/
    u_char ethernetIfMacAddress[6] =            {0x00,0x00,0x00,0x00,0x00,0x00};
    size_t ethernetIfMacAddress_len =           6; /*default size for representing ethernet MAC addresses, it should always be set to 6, otherwise an error will occur*/
    u_char ethernetIfIpAddress[4] =             {127, 0, 0, 1}; /*by default, loopback address is used*/
    size_t ethernetIfIpAddress_len =            4; /*default size for representing Internet IP addresses, it should always be set to 4, otherwise an error will occur*/
    u_char ethernetIfSubnetMask[4] =            {255, 255, 255, 0};
    size_t ethernetIfSubnetMask_len =           4; /*default size for representing Internet IP addresses, it should always be set to 4, otherwise an error will occur*/
    u_char ethernetIfIpAddressConflict[4] =     {0, 0, 0, 0};
    size_t ethernetIfIpAddressConflict_len =    4; /*default size for representing Internet IP addresses, it should always be set to 4, otherwise an error will occur*/


/** Initializes the ethernetIfTable module */
void
init_ethernetIfTable(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_ethernetIfTable();
}

/* Determine the first/last column names */


    /* Typical data structure for a row which is, refering to the MIB, ethernetIfTableEntry */
struct ethernetIfTableEntry {
    /* Index values */
    long ethernetIfIndex;

    /* Column values */
    long ethernetIfSpeed;
    u_char ethernetIfMacAddress[6];
    size_t ethernetIfMacAddress_len;
    u_char ethernetIfIpAddress[4];
    u_char old_ethernetIfIpAddress[4]; /* used for UNDO purposes*/
    size_t ethernetIfIpAddress_len;
    u_char ethernetIfSubnetMask[4];
    u_char old_ethernetIfSubnetMask[4]; /* used for UNDO purposes*/
    size_t ethernetIfSubnetMask_len;
    u_char ethernetIfIpAddressConflict[4];
    u_char old_ethernetIfIpAddressConflict[4]; /* used for UNDO purposes*/
    size_t ethernetIfIpAddressConflict_len;


    /* Illustrate using a simple linked list */
    int   valid;
    struct ethernetIfTableEntry *next;
};

/*this always represent the First row of the table*/
struct ethernetIfTableEntry  *ethernetIfTable_head;

/* create a new row in the (unsorted) table */
struct ethernetIfTableEntry * ethernetIfTableEntry_create(  long  ethernetIfIndex,
                                                            long ethernetIfSpeed,
                                                            u_char ethernetIfMacAddress[6],
                                                            size_t ethernetIfMacAddress_len,
                                                            u_char ethernetIfIpAddress[4],
                                                            size_t ethernetIfIpAddress_len,
                                                            u_char ethernetIfSubnetMask[4],
                                                             size_t ethernetIfSubnetMask_len,
                                                            u_char ethernetIfIpAddressConflict[4],
                                                            size_t ethernetIfIpAddressConflict_len )
{
    struct ethernetIfTableEntry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct ethernetIfTableEntry);
    if (!entry)
        return NULL;

    entry->ethernetIfIndex = ethernetIfIndex;
    entry->next = ethernetIfTable_head;
    entry->ethernetIfSpeed = ethernetIfSpeed;

    strcpy(entry->ethernetIfMacAddress, (char*)ethernetIfMacAddress);
    entry->ethernetIfMacAddress_len = ethernetIfMacAddress_len;

    strcpy((char*)entry->ethernetIfIpAddress,  (char*)ethernetIfIpAddress);
    entry->ethernetIfIpAddress_len = ethernetIfIpAddress_len;

    strcpy((char*)entry->ethernetIfSubnetMask,  (char*)ethernetIfSubnetMask);
    entry->ethernetIfSubnetMask_len = ethernetIfSubnetMask_len;

    strcpy((char*)entry->ethernetIfIpAddressConflict,  (char*)ethernetIfIpAddressConflict);
    entry->ethernetIfIpAddressConflict_len  = ethernetIfIpAddressConflict_len ;

    ethernetIfTable_head = entry;
    return entry;
}

/** Initialize the ethernetIfTable table by defining its contents and how it's structured */
void
initialize_table_ethernetIfTable(void)
{
    const oid ethernetIfTable_oid[] = {1,3,6,1,4,1,35990,3,1,1,12};
    const size_t ethernetIfTable_oid_len   = OID_LENGTH(ethernetIfTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("ethernetIfTable:init", "initializing table ethernetIfTable\n"));

    reg = netsnmp_create_handler_registration(
              "ethernetIfTable",     ethernetIfTable_handler,
              ethernetIfTable_oid, ethernetIfTable_oid_len,
              HANDLER_CAN_RWRITE
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER, /*index: ethernetIfIndex*/
                           0);
    table_info->min_column = COLUMN_ETHERNETIFSPEED;
    table_info->max_column = COLUMN_ETHERNETIFIPADDRESSCONFLICT;

    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = ethernetIfTable_get_first_data_point;
    iinfo->get_next_data_point  = ethernetIfTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;

    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialize the contents of the table here */

    ethernetIfTableEntry_create(ethernetIfIndex, ethernetIfSpeed,
                                ethernetIfMacAddress, ethernetIfMacAddress_len,
                                ethernetIfIpAddress, ethernetIfIpAddress_len,
                                ethernetIfSubnetMask, ethernetIfSubnetMask_len,
                                ethernetIfIpAddressConflict, ethernetIfIpAddressConflict_len);
}



/* remove a row from the table */
void
ethernetIfTable_removeEntry( struct ethernetIfTableEntry *entry ) {
    struct ethernetIfTableEntry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = ethernetIfTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        ethernetIfTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *  ethernetIfTable_get_first_data_point(  void **my_loop_context,
                                                                void **my_data_context,
                                                                netsnmp_variable_list *put_index_data,
                                                                netsnmp_iterator_info *mydata)
{
    *my_loop_context = ethernetIfTable_head;
    return ethernetIfTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list * ethernetIfTable_get_next_data_point(void **my_loop_context,
                                                            void **my_data_context,
                                                            netsnmp_variable_list *put_index_data,
                                                            netsnmp_iterator_info *mydata)
{
    struct ethernetIfTableEntry *entry = (struct ethernetIfTableEntry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->ethernetIfIndex );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the ethernetIfTable table */
int     ethernetIfTable_handler(    netsnmp_mib_handler               *handler,
                                    netsnmp_handler_registration      *reginfo,
                                    netsnmp_agent_request_info        *reqinfo,
                                    netsnmp_request_info              *requests) {

    netsnmp_request_info          *request;
    netsnmp_table_request_info    *table_info;
    struct ethernetIfTableEntry   *table_entry;
    int ret; /* it will be used to get the error and print it to the user*/
    int i; /*this is our loop variable*/

    DEBUGMSGTL(("ethernetIfTable:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct ethernetIfTableEntry *) netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);

            switch (table_info->colnum) {
            case COLUMN_ETHERNETIFSPEED:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb,
                                            ASN_INTEGER, table_entry->ethernetIfSpeed);
                break;


            case COLUMN_ETHERNETIFMACADDRESS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->ethernetIfMacAddress, table_entry->ethernetIfMacAddress_len);
                break;


            case COLUMN_ETHERNETIFIPADDRESS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_IPADDRESS,
                                            table_entry->ethernetIfIpAddress, table_entry->ethernetIfIpAddress_len);
                break;


            case COLUMN_ETHERNETIFSUBNETMASK:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_IPADDRESS,
                                            table_entry->ethernetIfSubnetMask, table_entry->ethernetIfSubnetMask_len);
                break;


            case COLUMN_ETHERNETIFIPADDRESSCONFLICT:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_IPADDRESS,
                                            table_entry->ethernetIfIpAddressConflict, table_entry->ethernetIfIpAddressConflict_len);
                break;


            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        for (request=requests; request; request=request->next) {
            table_entry = (struct ethernetIfTableEntry *) netsnmp_extract_iterator_context(request);
            table_info  =                                 netsnmp_extract_table_info      (request);

            switch (table_info->colnum) {
            case COLUMN_ETHERNETIFIPADDRESS:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_type(requests->requestvb, ASN_IPADDRESS);
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_ETHERNETIFSUBNETMASK:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_type(requests->requestvb, ASN_IPADDRESS);
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_ETHERNETIFIPADDRESSCONFLICT:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_type(requests->requestvb, ASN_IPADDRESS);
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            default:
                netsnmp_set_request_error( reqinfo, request,
                                           SNMP_ERR_NOTWRITABLE );
                return SNMP_ERR_NOERROR;
            }
        }
        break;

    case MODE_SET_RESERVE2:
        break;

    case MODE_SET_FREE:
        break;

    case MODE_SET_ACTION:
        for (request=requests; request; request=request->next) {
            table_entry = (struct ethernetIfTableEntry *) netsnmp_extract_iterator_context  (request);
            table_info  =                                 netsnmp_extract_table_info        (request);

            switch (table_info->colnum) {
            case COLUMN_ETHERNETIFIPADDRESS:
                strcpy(table_entry->old_ethernetIfIpAddress, table_entry->ethernetIfIpAddress);
                for(i=0; i<sizeof(table_entry->ethernetIfIpAddress)/sizeof(u_char); i++)
                    table_entry->ethernetIfIpAddress[i] = requests->requestvb->val.string[i];
                break;
            case COLUMN_ETHERNETIFSUBNETMASK:
                strcpy(table_entry->old_ethernetIfSubnetMask, table_entry->ethernetIfSubnetMask);
                for(i=0; i<sizeof(table_entry->ethernetIfSubnetMask )/sizeof(u_char); i++)
                    table_entry->ethernetIfSubnetMask [i] = requests->requestvb->val.string[i];
                break;
            case COLUMN_ETHERNETIFIPADDRESSCONFLICT:
                strcpy(table_entry->old_ethernetIfIpAddressConflict, table_entry->ethernetIfIpAddressConflict);
                for(i=0; i<sizeof(table_entry->ethernetIfIpAddressConflict )/sizeof(u_char); i++){
                    table_entry->ethernetIfIpAddressConflict [i] = requests->requestvb->val.string[i];
                }
                break;
            }
        }
        break;

    case MODE_SET_UNDO:
        for (request=requests; request; request=request->next) {
            table_entry = (struct ethernetIfTableEntry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);

            switch (table_info->colnum) {
            case COLUMN_ETHERNETIFIPADDRESS:
                strcpy( table_entry->ethernetIfIpAddress, table_entry->old_ethernetIfIpAddress);
                 for(i=0; i<sizeof(table_entry->old_ethernetIfIpAddress )/sizeof(u_char); i++)
                    table_entry->old_ethernetIfIpAddress[i] = 0;
                break;
            case COLUMN_ETHERNETIFSUBNETMASK:
                strcpy(table_entry->ethernetIfIpAddress,table_entry->old_ethernetIfIpAddress);
                for(i=0; i<sizeof(table_entry->old_ethernetIfSubnetMask )/sizeof(u_char); i++)
                    table_entry->old_ethernetIfSubnetMask[i] = 0;
                break;
            case COLUMN_ETHERNETIFIPADDRESSCONFLICT:
                strcpy(table_entry->ethernetIfIpAddress,table_entry->old_ethernetIfIpAddress );
                 for(i=0; i<sizeof(table_entry->old_ethernetIfIpAddressConflict )/sizeof(u_char); i++)
                    table_entry->old_ethernetIfIpAddressConflict[i] = 0;
                break;
            }
        }
        break;

    case MODE_SET_COMMIT:
        break;
    }
    return SNMP_ERR_NOERROR;
}
