/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef DEVICEMIBVERSION_H
#define DEVICEMIBVERSION_H

/* function declarations */
void init_deviceMibVersion(void);
Netsnmp_Node_Handler handle_deviceMibVersion;

#endif /* DEVICEMIBVERSION_H */
