/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef DEVICEPARTNUMBER_H
#define DEVICEPARTNUMBER_H

/* function declarations */
void init_devicePartNumber(void);
Netsnmp_Node_Handler handle_devicePartNumber;

#endif /* DEVICEPARTNUMBER_H */
