/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef DEVICEHARDWAREVERSION_H
#define DEVICEHARDWAREVERSION_H

/* function declarations */
void init_deviceHardwareVersion(void);
Netsnmp_Node_Handler handle_deviceHardwareVersion;

#endif /* DEVICEHARDWAREVERSION_H */
