/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef DEVICEUSERDESC_H
#define DEVICEUSERDESC_H

/* function declarations */
void init_deviceUserDesc(void);
Netsnmp_Node_Handler handle_deviceUserDesc;

#endif /* DEVICEUSERDESC_H */
