/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef DEVICENATOSTOCKNUMBER_H
#define DEVICENATOSTOCKNUMBER_H

/* function declarations */
void init_deviceNatoStockNumber(void);
Netsnmp_Node_Handler handle_deviceNatoStockNumber;

#endif /* DEVICENATOSTOCKNUMBER_H */
