/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef DEVICESERIALNUMBER_H
#define DEVICESERIALNUMBER_H

/* function declarations */
void init_deviceSerialNumber(void);
Netsnmp_Node_Handler handle_deviceSerialNumber;

#endif /* DEVICESERIALNUMBER_H */
