/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef DEVICERESET_H
#define DEVICERESET_H

/* function declarations */
void init_deviceReset(void);
Netsnmp_Node_Handler handle_deviceReset;

#endif /* DEVICERESET_H */
