/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef DEVICEMANUFACTURER_H
#define DEVICEMANUFACTURER_H

/* function declarations */
void init_deviceManufacturer(void);
Netsnmp_Node_Handler handle_deviceManufacturer;

#endif /* DEVICEMANUFACTURER_H */
