/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "ethernetIfTable.h"

/** Initialize the ethernetIfTable table by defining its contents and how it's structured */
void
initialize_table_ethernetIfTable(void)
{
    const oid ethernetIfTable_oid[] = {1,3,6,1,4,1,35990,3,1,1,12};
    netsnmp_table_data_set *table_set;

    /* create the table structure itself */
    table_set = netsnmp_create_table_data_set("ethernetIfTable");

    /* comment this out or delete if you don't support creation of new rows */
    table_set->allow_creation = 1;

    /***************************************************
     * Adding indexes
     */
    DEBUGMSGTL(("initialize_table_ethernetIfTable",
                "adding indexes to table ethernetIfTable\n"));
    netsnmp_table_set_add_indexes(table_set,
                           ASN_INTEGER,  /* index: ethernetIfIndex */
                           0);

    DEBUGMSGTL(("initialize_table_ethernetIfTable",
                "adding column types to table ethernetIfTable\n"));		 
    netsnmp_table_set_multi_add_default_row(table_set,
                                            COLUMN_ETHERNETIFINDEX, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_ETHERNETIFSPEED, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_ETHERNETIFMACADDRESS, ASN_OCTET_STR, 0,
                                            NULL, 0,
                                            COLUMN_ETHERNETIFIPADDRESS, ASN_IPADDRESS, 1,
                                            NULL, 0,
                                            COLUMN_ETHERNETIFSUBNETMASK, ASN_IPADDRESS, 1,
                                            NULL, 0,
                                            COLUMN_ETHERNETIFIPADDRESSCONFLICT, ASN_IPADDRESS, 1,
                                            NULL, 0,
                              0);
    
    /* registering the table with the master agent */
    /* note: if you don't need a subhandler to deal with any aspects
       of the request, change ethernetIfTable_handler to "NULL" */
    netsnmp_register_table_data_set(netsnmp_create_handler_registration("ethernetIfTable", ethernetIfTable_handler,
                                                        ethernetIfTable_oid,
                                                        OID_LENGTH(ethernetIfTable_oid),
                                                        HANDLER_CAN_RWRITE),
                            table_set, NULL);
}

/** Initializes the ethernetIfTable module */
void
init_ethernetIfTable(void)
{

  /* here we initialize all the tables we're planning on supporting */
    initialize_table_ethernetIfTable();
}

/** handles requests for the ethernetIfTable table, if anything else needs to be done */
int
ethernetIfTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {
    /* perform anything here that you need to do.  The requests have
       already been processed by the master table_dataset handler, but
       this gives you chance to act on the request in some other way
       if need be. */
    return SNMP_ERR_NOERROR;
}
