# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: OpenVivoe Website 
email: hoel.vasseur@openwide.fr
description: > # this means to ignore newlines until "baseurl:"
  VIVOE is a military norm to stream video from several sources to
  several sinks. Video streaming uses is based on RTP and SAP/SDP
  while streaming management uses SNMP. OpenVivoe is the Open Source
  impementation realized by OpenWide Ingenierie, a French Open Source
  architecte.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: OpenWide_Inge
github_username: Openwide-Ingenierie

# Build settings
markdown: kramdown
